### ISSUE TITLE
error "Can't set headers after they are sent"

### ISSUE THREAD

**Issue by clyra** [sebastianlinz/FanControl#1]
HI,

Thank you for the fan control! It was working right but a few days ago it stopped and I'm seeing the error below. I guess the zwift guys changed something...

Tue Aug 14 2018 11:29:25 GMT+0000 (UTC) - debug: ZwiftAdapter.constructor()
Tue Aug 14 2018 11:29:30 GMT+0000 (UTC) - debug: playerId: <xxxxx>
GET / 200 287.253 ms - 873
GET /stylesheets/style.css 200 5.808 ms - 782
Tue Aug 14 2018 11:29:47 GMT+0000 (UTC) - debug: /getFanLevel fanState: 0, fanLevel: [0]
GET /getFanLevel 200 3.968 ms - 61
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (/app/node_modules/express/lib/response.js:730:10)
    at ServerResponse.send (/app/node_modules/express/lib/response.js:170:12)
    at done (/app/node_modules/express/lib/response.js:967:10)
    at Object.exports.renderFile (/app/node_modules/jade/lib/index.js:374:12)
    at View.exports.__express [as engine] (/app/node_modules/jade/lib/index.js:417:11)
    at View.render (/app/node_modules/express/lib/view.js:127:8)
    at tryRender (/app/node_modules/express/lib/application.js:640:10)
    at Function.render (/app/node_modules/express/lib/application.js:592:3)

**Comment by sebastianlinz** [comment]
Hi,

could you please try again if the issue still exists. Sorry for late response.

Kind regards,

Sebastian

**Comment by rogeriocm** [comment]
Mon Dec 03 2018 15:15:10 GMT-0200 (GMT-02:00) - debug: ZwiftAdapter.constructor()
(node:6208) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at ZwiftAdapter.account.getWorld.riders.then.catch.error (C:\FanControl-master\ZwiftAdapter.js:17:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6208) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by clyra** [comment]
Hi,

Sorry for the even later response. I used your code as inspiration to write my own version of the fan control but using a python library. I hope rogeriocm could help in testing your fix. cya.

**Comment by rogeriocm** [comment]
fancontroller worked perfectly, after the zwift update, the system no longer connects to the zwfit, the ventilator only works in the manual mode. I tried to do it all over again but the error continues.

**Comment by rogeriocm** [comment]
https://github.com/WebReflection/circular-json

**Comment by rogeriocm** [comment]
GDPR and Zwift's Developer API
In July '08, this library was converted to use Zwift's new Developer API, in accordance with Zwift's policies.
The Developer API requires a special developer account, and won't work with regular rider accounts like before. Currently, Zwift is not able to offer developer accounts to hobby developers, but I'm hoping they'll be able to at some point. You can contact Zwift at developers@zwift.com to register interest and ask for further information.

**Comment by clyra** [comment]
@rogeriocm yes, that's true, but somehow it still works. I'm using this library: https://pypi.org/project/zwift-client/ and it works fine.

**Comment by rogeriocm** [comment]
thanks
I will try this!
